### PR TITLE
Update HIP CI configuration to HIP 5.6

### PR DESCRIPTION
**Pull request by msimberg**

### CODE REVIEW

**Comment by msimberg** [comment]
It seems like HIP 5.7 triggers the error:
```
/opt/spack-6cfcbc01679ebabe640f4462c8fc07626a543015/opt/spack/linux-ubuntu22.04-zen3/gcc-12.2.0/stdexec-git.nvhpc-23.09.rc4_main-fu7ialflbf3rvcwd2zxjs5fg64c72mlf/include/stdexec/execution.hpp:6339:44: error: out-of-line definition of 'operator()' does not match any declaration in 'get_completion_scheduler_t<_CPO>'
    auto get_completion_scheduler_t<_CPO>::operator()(const _Queryable& __queryable) const noexcept
                                           ^~~~~~~~
```
with an otherwise unchanged environment (in particular, same version of stdexec).

**Comment by msimberg** [comment]
I'll return to this once the CSCS maintenance is over and I can test more. For anyone bumping this into the meantime, using pika with stdexec and HIP requires using HIP version 5.5 or 5.6 at most. 5.7 will not work for the moment.

**Comment by msimberg** [comment]
I'll use this branch to try bumping the spack commit used with HIP 5.5 first (which is failing on other PRs), then get back to bumping HIP from 5.5 to 5.7 (or 6.X).

**Comment by msimberg** [comment]
Curiously things start failing with https://github.com/spack/spack/commit/d0589285f72bc6ec9b5f804612448954dcdf819c. Makes no sense to me at the moment...

**Comment by msimberg** [comment]
https://github.com/spack/spack/pull/45788 should work around the build issues. It seems like there's some sort of issue caused by a new version of ninja, though I don't know what exactly triggers it.

I'm going to get #1205 in before this. Based on the error message I suspect a newer stdexec might fix the issue mentioned above with HIP 5.7:

```
/opt/spack-6cfcbc01679ebabe640f4462c8fc07626a543015/opt/spack/linux-ubuntu22.04-zen3/gcc-12.2.0/stdexec-git.nvhpc-23.09.rc4_main-fu7ialflbf3rvcwd2zxjs5fg64c72mlf/include/stdexec/execution.hpp:6339:44: error: out-of-line definition of 'operator()' does not match any declaration in 'get_completion_scheduler_t<_CPO>'
    auto get_completion_scheduler_t<_CPO>::operator()(const _Queryable& __queryable) const noexcept
                                           ^~~~~~~~
```

**Comment by msimberg** [comment]
stdexec simply doesn't compile with HIP 5.7: https://compiler-explorer.com/z/jEYz9qjTv. Since 5.6 and older, as well as 6.0 and newer don't fail the same way I'm going to assume this is simply a HIP 5.7 issue (and I'll add a corresponding conflict to spack).

I'll try to get HIP updated to 5.6 in this PR though (and separately, add a HIP 6 configuration: #1164).
